services: 
  web-app:
    image: ${DOCKER_USERNAME}/plw-tests:${IMAGE_TAG:-latest}
    command: npm start
    ports:
      - "4200:4200"
    healthcheck:
      # Використовуємо wget, він частіше є в образах, ніж curl
      test: ["CMD-SHELL", "wget -q --spider http://localhost:4200 || exit 1"]
      interval: 15s      # Робити перевірку кожні 15 секунд
      timeout: 10s       # Чекати відповіді від wget до 10 секунд
      retries: 12        # 12 спроб по 15 секунд = 180 секунд (3 хвилини)
      start_period: 120s # Дві хвилини "фори" на компіляцію перед початком перевірок

  playwright-test:
    container_name: my-tests
    image: ${DOCKER_USERNAME}/plw-tests:${IMAGE_TAG:-latest}
    depends_on:
      web-app:
        condition: service_healthy # чекатиме, поки сервер "прокинеться"
    environment:
      - BASE_URL=http://web-app:4200 # звертайся до сервера за іменем сервісу
    command: npm run test:docker
    volumes: 
      - ./tests/playwright-report/:/app/tests/playwright-report
      - ./tests/test-results/:/app/tests/test-results
